import os
path = r"app\src\main\java\com\app\knowledgegraph\ui\components\MathView.kt"

lines = []
lines.append('package com.app.knowledgegraph.ui.components')
lines.append('')
lines.append('import android.annotation.SuppressLint')
lines.append('import android.view.ViewGroup')
lines.append('import android.webkit.WebView')
lines.append('import android.webkit.WebViewClient')
lines.append('import android.webkit.WebSettings')
lines.append('import androidx.compose.runtime.*')
lines.append('import androidx.compose.ui.Modifier')
lines.append('import androidx.compose.ui.viewinterop.AndroidView')
lines.append('import androidx.compose.foundation.layout.heightIn')
lines.append('import androidx.compose.foundation.layout.fillMaxWidth')
lines.append('import androidx.compose.ui.unit.dp')
lines.append('')
lines.append('@SuppressLint("SetJavaScriptEnabled")')
lines.append('@Composable')
lines.append('fun MathView(')
lines.append('    text: String,')
lines.append('    modifier: Modifier = Modifier,')
lines.append('    figureSvg: String = "",')
lines.append('    baseFontSize: Int = 16')
lines.append(') {')
lines.append('    if (text.isBlank() && figureSvg.isBlank()) return')
lines.append('')
lines.append('    val fullHtml = remember(text, figureSvg, baseFontSize) {')
lines.append('        buildFullHtml(text, figureSvg, baseFontSize)')
lines.append('    }')
lines.append('')
lines.append('    AndroidView(')
lines.append('        modifier = modifier.fillMaxWidth().heightIn(min = 48.dp),')
lines.append('        factory = { ctx ->')
lines.append('            WebView(ctx).apply {')
lines.append('                layoutParams = ViewGroup.LayoutParams(')
lines.append('                    ViewGroup.LayoutParams.MATCH_PARENT,')
lines.append('                    ViewGroup.LayoutParams.WRAP_CONTENT')
lines.append('                )')
lines.append('                settings.javaScriptEnabled = true')
lines.append('                settings.domStorageEnabled = true')
lines.append('                settings.loadWithOverviewMode = true')
lines.append('                settings.useWideViewPort = false')
lines.append('                settings.cacheMode = WebSettings.LOAD_DEFAULT')
lines.append('                setBackgroundColor(android.graphics.Color.TRANSPARENT)')
lines.append('                isVerticalScrollBarEnabled = false')
lines.append('                isHorizontalScrollBarEnabled = false')
lines.append('                webViewClient = object : WebViewClient() {}')
lines.append('                loadDataWithBaseURL("https://cdn.jsdelivr.net", fullHtml, "text/html", "UTF-8", null)')
lines.append('            }')
lines.append('        },')
lines.append('        update = { webView ->')
lines.append('            webView.loadDataWithBaseURL("https://cdn.jsdelivr.net", fullHtml, "text/html", "UTF-8", null)')
lines.append('        }')
lines.append('    )')
lines.append('}')
lines.append('')
lines.append('private fun buildFullHtml(text: String, figureSvg: String, fontSize: Int): String {')
lines.append('    val d = "$"')
lines.append('    val escapedContent = escapeHtmlPreservingMath(text)')
lines.append('    val svgBlock = if (figureSvg.isNotBlank()) "<div style=\'text-align:center;margin:12px 0\'>" + figureSvg + "</div>" else ""')
lines.append('    val katexCss = "https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/katex.min.css"')
lines.append('    val katexJs = "https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/katex.min.js"')
lines.append('    val autoRenderJs = "https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/contrib/auto-render.min.js"')
lines.append('    return "<!DOCTYPE html><html><head>" +')
lines.append('        "<meta charset=\'utf-8\'>" +')
lines.append('        "<meta name=\'viewport\' content=\'width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no\'>" +')
lines.append('        "<link rel=\'stylesheet\' href=\'" + katexCss + "\'>" +')
lines.append('        "<script src=\'" + katexJs + "\'></script>" +')
lines.append('        "<script src=\'" + autoRenderJs + "\'></script>" +')
lines.append('        "<style>" +')
lines.append('        "*{margin:0;padding:0;box-sizing:border-box}" +')
lines.append('        "body{font-family:-apple-system,system-ui,sans-serif;font-size:" + fontSize + "px;" +')
lines.append('        "line-height:1.7;color:#1a1a1a;padding:8px 4px;word-wrap:break-word;background:transparent}" +')
lines.append('        ".katex{font-size:1.1em}" +')
lines.append('        ".katex-display{margin:8px 0;overflow-x:auto;overflow-y:hidden}" +')
lines.append('        "</style></head><body>" +')
lines.append('        "<div id=\'content\'>" + escapedContent + svgBlock + "</div>" +')
lines.append('        "<script>" +')
lines.append('        "document.addEventListener(\'DOMContentLoaded\',function(){" +')
lines.append('        "try{if(window.renderMathInElement){renderMathInElement(document.getElementById(\'content\'),{" +')
lines.append('        "delimiters:[" +')
lines.append('        "{left:\'" + d + d + "\',right:\'" + d + d + "\',display:true}," +')
lines.append('        "{left:\'" + d + "\',right:\'" + d + "\',display:false}" +')
lines.append('        "],throwOnError:false})}}catch(e){}});" +')
lines.append('        "</script></body></html>"')
lines.append('}')
lines.append('')
lines.append('private fun escapeHtmlPreservingMath(input: String): String {')
lines.append('    val result = StringBuilder()')
lines.append('    var i = 0')
lines.append('    while (i < input.length) {')
lines.append('        when {')
lines.append('            i + 1 < input.length && input[i] == \'$\' && input[i + 1] == \'$\' -> {')
lines.append('                val end = input.indexOf("$$", i + 2)')
lines.append('                if (end >= 0) { result.append(input.substring(i, end + 2)); i = end + 2 }')
lines.append('                else { result.append("$$"); i += 2 }')
lines.append('            }')
lines.append('            input[i] == \'$\' -> {')
lines.append('                val end = input.indexOf(\'$\', i + 1)')
lines.append('                if (end >= 0) { result.append(input.substring(i, end + 1)); i = end + 1 }')
lines.append('                else { result.append("$"); i += 1 }')
lines.append('            }')
lines.append("            input[i] == '\\n' -> { result.append(\"<br>\"); i += 1 }")
lines.append('            input[i] == \'&\' -> { result.append("&amp;"); i += 1 }')
lines.append('            input[i] == \'<\' -> { result.append("&lt;"); i += 1 }')
lines.append('            input[i] == \'>\' -> { result.append("&gt;"); i += 1 }')
lines.append('            else -> { result.append(input[i]); i += 1 }')
lines.append('        }')
lines.append('    }')
lines.append('    return result.toString()')
lines.append('}')

with open(path, "w", encoding="utf-8") as f:
    f.write("\n".join(lines) + "\n")
print("done: MathView.kt")
