import os
d = r"app\src\main\java\com\app\knowledgegraph\ui\smartscan"

lines = []
a = lines.append
a('package com.app.knowledgegraph.ui.smartscan')
a('')
a('import android.Manifest')
a('import android.content.pm.PackageManager')
a('import android.graphics.Bitmap')
a('import android.graphics.BitmapFactory')
a('import android.net.Uri')
a('import androidx.activity.compose.rememberLauncherForActivityResult')
a('import androidx.activity.result.contract.ActivityResultContracts')
a('import androidx.compose.foundation.layout.*')
a('import androidx.compose.foundation.lazy.LazyColumn')
a('import androidx.compose.foundation.lazy.itemsIndexed')
a('import androidx.compose.material.icons.Icons')
a('import androidx.compose.material.icons.automirrored.filled.ArrowBack')
a('import androidx.compose.material.icons.filled.*')
a('import androidx.compose.material3.*')
a('import androidx.compose.runtime.*')
a('import androidx.compose.runtime.saveable.rememberSaveable')
a('import androidx.compose.ui.Alignment')
a('import androidx.compose.ui.Modifier')
a('import androidx.compose.ui.platform.LocalContext')
a('import androidx.compose.ui.text.font.FontWeight')
a('import androidx.compose.ui.text.style.TextOverflow')
a('import androidx.compose.ui.unit.dp')
a('import androidx.core.content.ContextCompat')
a('import androidx.core.content.FileProvider')
a('import androidx.lifecycle.viewmodel.compose.viewModel')
a('import com.app.knowledgegraph.AppContainer')
a('import com.app.knowledgegraph.data.db.entity.Card')
a('import java.io.File')
a('')
a('@OptIn(ExperimentalMaterial3Api::class)')
a('@Composable')
a('fun SmartScanScreen(')
a('    container: AppContainer,')
a('    subject: String,')
a('    onNavigateBack: () -> Unit,')
a('    viewModel: SmartScanViewModel = viewModel(factory = SmartScanViewModel.factory(container))')
a(') {')
a('    val uiState by viewModel.uiState.collectAsState()')
a('    val context = LocalContext.current')
a('')
a('    LaunchedEffect(subject) { viewModel.setSubject(subject) }')
a('')
a('    var photoFilePath by rememberSaveable { mutableStateOf<String?>(null) }')
a('')
a('    fun getImageDir(): File {')
a('        val dir = File(context.cacheDir, "smart_images")')
a('        dir.mkdirs()')
a('        return dir')
a('    }')
a('')
a('    fun createCameraFileAndUri(): Pair<String, Uri> {')
a('        val file = File(getImageDir(), "smart_" + System.currentTimeMillis() + ".jpg")')
a('        val uri = FileProvider.getUriForFile(context, context.packageName + ".fileprovider", file)')
a('        return file.absolutePath to uri')
a('    }')
a('')
a('    fun decodeBitmapFromFile(path: String): Bitmap? {')
a('        val file = File(path)')
a('        if (!file.exists() || file.length() == 0L) return null')
a('        return try {')
a('            BitmapFactory.decodeFile(path)')
a('                ?: BitmapFactory.decodeFile(path, BitmapFactory.Options().apply { inSampleSize = 2 })')
a('        } catch (_: OutOfMemoryError) {')
a('            BitmapFactory.decodeFile(path, BitmapFactory.Options().apply { inSampleSize = 4 })')
a('        }')
a('    }')
a('')
a('    // Camera launcher')
a('    val cameraLauncher = rememberLauncherForActivityResult(ActivityResultContracts.TakePicture()) { success ->')
a('        if (success) {')
a('            val path = photoFilePath')
a('            if (path != null) {')
a('                val bitmap = decodeBitmapFromFile(path)')
a('                if (bitmap != null) viewModel.processImage(bitmap)')
a('                else viewModel.resetToIdle()')
a('            }')
a('        }')
a('    }')
a('')
a('    // Permission launcher')
a('    val permissionLauncher = rememberLauncherForActivityResult(ActivityResultContracts.RequestPermission()) { granted ->')
a('        if (granted) {')
a('            val (path, uri) = createCameraFileAndUri()')
a('            photoFilePath = path')
a('            cameraLauncher.launch(uri)')
a('        }')
a('    }')
a('')
a('    fun launchCamera() {')
a('        val hasPerm = ContextCompat.checkSelfPermission(context, Manifest.permission.CAMERA) == PackageManager.PERMISSION_GRANTED')
a('        if (hasPerm) {')
a('            val (path, uri) = createCameraFileAndUri()')
a('            photoFilePath = path')
a('            cameraLauncher.launch(uri)')
a('        } else {')
a('            permissionLauncher.launch(Manifest.permission.CAMERA)')
a('        }')
a('    }')
a('')
a('    // Auto-launch camera on first open')
a('    var cameraLaunched by rememberSaveable { mutableStateOf(false) }')
a('    LaunchedEffect(Unit) {')
a('        if (!cameraLaunched && uiState.phase == SmartScanPhase.IDLE) {')
a('            cameraLaunched = true')
a('            launchCamera()')
a('        }')
a('    }')
a('')
a('    Scaffold(')
a('        topBar = {')
a('            TopAppBar(')
a('                title = { Text("\\u667a\\u80fd\\u626b\\u63cf - " + subject) },')
a('                navigationIcon = {')
a('                    IconButton(onClick = onNavigateBack) {')
a('                        Icon(Icons.AutoMirrored.Filled.ArrowBack, "\\u8fd4\\u56de")')
a('                    }')
a('                }')
a('            )')
a('        }')
a('    ) { padding ->')
a('        when (uiState.phase) {')
a('            SmartScanPhase.IDLE -> {')
a('                IdleContent(')
a('                    uiState = uiState,')
a('                    onCamera = { launchCamera() },')
a('                    modifier = Modifier.padding(padding)')
a('                )')
a('            }')
a('            SmartScanPhase.PROCESSING -> {')
a('                ProcessingContent(uiState = uiState, modifier = Modifier.padding(padding))')
a('            }')
a('            SmartScanPhase.PREVIEW -> {')
a('                PreviewContent(')
a('                    uiState = uiState,')
a('                    onToggle = viewModel::toggleCard,')
a('                    onSelectAll = viewModel::selectAll,')
a('                    onSave = viewModel::saveSelected,')
a('                    onBack = viewModel::resetToIdle,')
a('                    modifier = Modifier.padding(padding)')
a('                )')
a('            }')
a('            SmartScanPhase.SAVED -> {')
a('                SavedContent(')
a('                    savedCount = uiState.savedCount,')
a('                    onContinue = { cameraLaunched = false; viewModel.resetToIdle() },')
a('                    onDone = onNavigateBack,')
a('                    modifier = Modifier.padding(padding)')
a('                )')
a('            }')
a('        }')
a('    }')
a('}')
a('')
a('@Composable')
a('private fun IdleContent(uiState: SmartScanUiState, onCamera: () -> Unit, modifier: Modifier) {')
a('    Column(')
a('        modifier = modifier.fillMaxSize().padding(16.dp),')
a('        verticalArrangement = Arrangement.Center,')
a('        horizontalAlignment = Alignment.CenterHorizontally')
a('    ) {')
a('        if (uiState.error != null) {')
a('            Card(colors = CardDefaults.cardColors(containerColor = MaterialTheme.colorScheme.errorContainer)) {')
a('                Text(uiState.error, modifier = Modifier.padding(16.dp), color = MaterialTheme.colorScheme.onErrorContainer)')
a('            }')
a('            Spacer(Modifier.height(16.dp))')
a('        }')
a('        Button(onClick = onCamera, modifier = Modifier.height(56.dp)) {')
a('            Icon(Icons.Default.CameraAlt, null)')
a('            Spacer(Modifier.width(8.dp))')
a('            Text("\\u62cd\\u7167\\u8bc6\\u522b")')
a('        }')
a('    }')
a('}')
a('')
a('@Composable')
a('private fun ProcessingContent(uiState: SmartScanUiState, modifier: Modifier) {')
a('    Box(modifier = modifier.fillMaxSize(), contentAlignment = Alignment.Center) {')
a('        Column(horizontalAlignment = Alignment.CenterHorizontally, verticalArrangement = Arrangement.spacedBy(12.dp)) {')
a('            CircularProgressIndicator()')
a('            Text(uiState.progressMessage.ifBlank { "AI \\u6b63\\u5728\\u8bc6\\u522b..." },')
a('                style = MaterialTheme.typography.bodyMedium, color = MaterialTheme.colorScheme.onSurfaceVariant)')
a('        }')
a('    }')
a('}')
a('')
a('@Composable')
a('private fun PreviewContent(')
a('    uiState: SmartScanUiState,')
a('    onToggle: (Int) -> Unit,')
a('    onSelectAll: () -> Unit,')
a('    onSave: () -> Unit,')
a('    onBack: () -> Unit,')
a('    modifier: Modifier')
a(') {')
a('    Column(modifier = modifier.fillMaxSize()) {')
a('        Row(')
a('            modifier = Modifier.fillMaxWidth().padding(horizontal = 16.dp, vertical = 8.dp),')
a('            horizontalArrangement = Arrangement.SpaceBetween,')
a('            verticalAlignment = Alignment.CenterVertically')
a('        ) {')
a('            Text("\\u751f\\u6210 " + uiState.generatedCards.size + " \\u5f20\\u5361\\u7247",')
a('                style = MaterialTheme.typography.titleMedium, fontWeight = FontWeight.Bold)')
a('            Row(horizontalArrangement = Arrangement.spacedBy(8.dp)) {')
a('                TextButton(onClick = onSelectAll) {')
a('                    Text(if (uiState.selectedIndices.size == uiState.generatedCards.size) "\\u53d6\\u6d88\\u5168\\u9009" else "\\u5168\\u9009")')
a('                }')
a('                TextButton(onClick = onBack) { Text("\\u91cd\\u65b0\\u626b\\u63cf") }')
a('            }')
a('        }')
a('')
a('        LazyColumn(')
a('            modifier = Modifier.weight(1f),')
a('            contentPadding = PaddingValues(horizontal = 16.dp),')
a('            verticalArrangement = Arrangement.spacedBy(8.dp)')
a('        ) {')
a('            itemsIndexed(uiState.generatedCards) { index, card ->')
a('                CardPreviewItem(')
a('                    index = index,')
a('                    card = card,')
a('                    isSelected = uiState.selectedIndices.contains(index),')
a('                    onToggle = { onToggle(index) }')
a('                )')
a('            }')
a('        }')
a('')
a('        Button(')
a('            onClick = onSave,')
a('            modifier = Modifier.fillMaxWidth().padding(16.dp).height(52.dp),')
a('            enabled = uiState.selectedIndices.isNotEmpty()')
a('        ) {')
a('            Text("\\u4fdd\\u5b58\\u9009\\u4e2d\\u7684 " + uiState.selectedIndices.size + " \\u5f20\\u5361\\u7247")')
a('        }')
a('    }')
a('}')
a('')
a('@Composable')
a('private fun CardPreviewItem(index: Int, card: Card, isSelected: Boolean, onToggle: () -> Unit) {')
a('    Card(')
a('        colors = CardDefaults.cardColors(')
a('            containerColor = if (isSelected) MaterialTheme.colorScheme.primaryContainer.copy(alpha = 0.3f)')
a('            else MaterialTheme.colorScheme.surfaceContainerLow')
a('        )')
a('    ) {')
a('        Row(modifier = Modifier.padding(12.dp), verticalAlignment = Alignment.Top) {')
a('            Checkbox(checked = isSelected, onCheckedChange = { onToggle() })')
a('            Spacer(Modifier.width(8.dp))')
a('            Column(modifier = Modifier.weight(1f)) {')
a('                Row(verticalAlignment = Alignment.CenterVertically, horizontalArrangement = Arrangement.spacedBy(8.dp)) {')
a('                    AssistChip(onClick = {}, label = { Text(card.type.name, style = MaterialTheme.typography.labelSmall) }, modifier = Modifier.height(24.dp))')
a('                    Text("#" + (index + 1), style = MaterialTheme.typography.labelMedium, color = MaterialTheme.colorScheme.onSurfaceVariant)')
a('                }')
a('                Spacer(Modifier.height(4.dp))')
a('                Text(card.prompt, style = MaterialTheme.typography.bodyMedium, fontWeight = FontWeight.Medium, maxLines = 2, overflow = TextOverflow.Ellipsis)')
a('                if (card.answer.isNotBlank()) {')
a('                    Spacer(Modifier.height(4.dp))')
a('                    Text(card.answer, style = MaterialTheme.typography.bodySmall, color = MaterialTheme.colorScheme.onSurfaceVariant, maxLines = 3, overflow = TextOverflow.Ellipsis)')
a('                }')
a('            }')
a('        }')
a('    }')
a('}')
a('')
a('@Composable')
a('private fun SavedContent(savedCount: Int, onContinue: () -> Unit, onDone: () -> Unit, modifier: Modifier) {')
a('    Box(modifier = modifier.fillMaxSize(), contentAlignment = Alignment.Center) {')
a('        Column(horizontalAlignment = Alignment.CenterHorizontally, verticalArrangement = Arrangement.spacedBy(16.dp), modifier = Modifier.padding(32.dp)) {')
a('            Icon(Icons.Default.CheckCircle, null, tint = MaterialTheme.colorScheme.primary, modifier = Modifier.size(64.dp))')
a('            Text("\\u6210\\u529f\\u4fdd\\u5b58 " + savedCount + " \\u5f20\\u5361\\u7247", style = MaterialTheme.typography.headlineSmall, fontWeight = FontWeight.Bold)')
a('            Button(onClick = onContinue, modifier = Modifier.fillMaxWidth(0.7f)) {')
a('                Icon(Icons.Default.CameraAlt, null)')
a('                Spacer(Modifier.width(8.dp))')
a('                Text("\\u7ee7\\u7eed\\u626b\\u63cf")')
a('            }')
a('            OutlinedButton(onClick = onDone, modifier = Modifier.fillMaxWidth(0.7f)) {')
a('                Text("\\u8fd4\\u56de Library")')
a('            }')
a('        }')
a('    }')
a('}')

with open(os.path.join(d, "SmartScanScreen.kt"), "w", encoding="utf-8") as f:
    f.write("\n".join(lines) + "\n")
print("done: SmartScanScreen.kt")
