import os
d = r"app\src\main\java\com\app\knowledgegraph\ui\smartscan"
os.makedirs(d, exist_ok=True)

lines = []
a = lines.append
a('package com.app.knowledgegraph.ui.smartscan')
a('')
a('import android.graphics.Bitmap')
a('import androidx.lifecycle.ViewModel')
a('import androidx.lifecycle.ViewModelProvider')
a('import androidx.lifecycle.viewModelScope')
a('import com.app.knowledgegraph.AppContainer')
a('import com.app.knowledgegraph.data.db.entity.Card')
a('import com.app.knowledgegraph.data.db.entity.CardType')
a('import com.app.knowledgegraph.data.network.DeepSeekApi')
a('import com.app.knowledgegraph.data.preferences.SettingsDataStore')
a('import com.app.knowledgegraph.data.repository.CardRepository')
a('import kotlinx.coroutines.Dispatchers')
a('import kotlinx.coroutines.flow.MutableStateFlow')
a('import kotlinx.coroutines.flow.StateFlow')
a('import kotlinx.coroutines.flow.asStateFlow')
a('import kotlinx.coroutines.flow.first')
a('import kotlinx.coroutines.flow.update')
a('import kotlinx.coroutines.launch')
a('import kotlinx.coroutines.withContext')
a('')
a('enum class SmartScanPhase { IDLE, PROCESSING, PREVIEW, SAVED }')
a('')
a('data class SmartScanUiState(')
a('    val phase: SmartScanPhase = SmartScanPhase.IDLE,')
a('    val subject: String = "",')
a('    val generatedCards: List<Card> = emptyList(),')
a('    val selectedIndices: Set<Int> = emptySet(),')
a('    val isProcessing: Boolean = false,')
a('    val progressMessage: String = "",')
a('    val error: String? = null,')
a('    val savedCount: Int = 0,')
a('    val apiKeyPresent: Boolean = false')
a(')')
a('')
a('class SmartScanViewModel(')
a('    private val cardRepository: CardRepository,')
a('    private val deepSeekApi: DeepSeekApi,')
a('    private val settingsDataStore: SettingsDataStore')
a(') : ViewModel() {')
a('')
a('    private val _uiState = MutableStateFlow(SmartScanUiState())')
a('    val uiState: StateFlow<SmartScanUiState> = _uiState.asStateFlow()')
a('')
a('    init {')
a('        viewModelScope.launch {')
a('            settingsDataStore.apiKeyFlow.collect { key ->')
a('                _uiState.update { it.copy(apiKeyPresent = key.isNotBlank()) }')
a('            }')
a('        }')
a('    }')
a('')
a('    fun setSubject(subject: String) {')
a('        _uiState.update { it.copy(subject = subject) }')
a('    }')
a('')
a('    fun processImage(bitmap: Bitmap) {')
a('        viewModelScope.launch {')
a('            _uiState.update { it.copy(phase = SmartScanPhase.PROCESSING, isProcessing = true, error = null) }')
a('')
a('            val apiKey = settingsDataStore.apiKeyFlow.first()')
a('            if (apiKey.isBlank()) {')
a('                _uiState.update { it.copy(isProcessing = false, error = "\\u8bf7\\u5148\\u914d\\u7f6e API Key", phase = SmartScanPhase.IDLE) }')
a('                return@launch')
a('            }')
a('')
a('            val baseUrl = settingsDataStore.apiBaseUrlFlow.first()')
a('            val model = settingsDataStore.apiModelFlow.first()')
a('            val subject = _uiState.value.subject')
a('')
a('            val result = withContext(Dispatchers.IO) {')
a('                deepSeekApi.smartScanToCards(apiKey, bitmap, subject, baseUrl, model) { msg ->')
a('                    _uiState.update { it.copy(progressMessage = msg) }')
a('                }')
a('            }')
a('')
a('            result.fold(')
a('                onSuccess = { cardMaps ->')
a('                    val cards = cardMaps.map { m ->')
a('                        val cardType = try { CardType.valueOf(m["type"] ?: "CONCEPT") } catch (_: Exception) { CardType.CONCEPT }')
a('                        Card(')
a('                            type = cardType,')
a('                            chapter = m["chapter"] ?: subject,')
a('                            tags = m["tags"] ?: subject,')
a('                            prompt = m["prompt"] ?: "",')
a('                            hint = m["hint"] ?: "",')
a('                            answer = m["answer"] ?: ""')
a('                        )')
a('                    }')
a('                    _uiState.update {')
a('                        it.copy(')
a('                            phase = SmartScanPhase.PREVIEW,')
a('                            generatedCards = cards,')
a('                            selectedIndices = cards.indices.toSet(),')
a('                            isProcessing = false')
a('                        )')
a('                    }')
a('                },')
a('                onFailure = { e ->')
a('                    _uiState.update { it.copy(isProcessing = false, error = e.message, phase = SmartScanPhase.IDLE) }')
a('                }')
a('            )')
a('        }')
a('    }')
a('')
a('    fun toggleCard(index: Int) {')
a('        _uiState.update { state ->')
a('            val newSet = state.selectedIndices.toMutableSet()')
a('            if (newSet.contains(index)) newSet.remove(index) else newSet.add(index)')
a('            state.copy(selectedIndices = newSet)')
a('        }')
a('    }')
a('')
a('    fun selectAll() {')
a('        _uiState.update { state ->')
a('            if (state.selectedIndices.size == state.generatedCards.size)')
a('                state.copy(selectedIndices = emptySet())')
a('            else')
a('                state.copy(selectedIndices = state.generatedCards.indices.toSet())')
a('        }')
a('    }')
a('')
a('    fun saveSelected() {')
a('        viewModelScope.launch {')
a('            val state = _uiState.value')
a('            val selected = state.selectedIndices.map { state.generatedCards[it] }')
a('            if (selected.isEmpty()) return@launch')
a('            cardRepository.insertCards(selected)')
a('            _uiState.update { it.copy(phase = SmartScanPhase.SAVED, savedCount = selected.size) }')
a('        }')
a('    }')
a('')
a('    fun resetToIdle() {')
a('        _uiState.update { SmartScanUiState(subject = it.subject, apiKeyPresent = it.apiKeyPresent) }')
a('    }')
a('')
a('    companion object {')
a('        fun factory(container: AppContainer) = object : ViewModelProvider.Factory {')
a('            @Suppress("UNCHECKED_CAST")')
a('            override fun <T : ViewModel> create(modelClass: Class<T>): T {')
a('                return SmartScanViewModel(container.cardRepository, DeepSeekApi(), container.settingsDataStore) as T')
a('            }')
a('        }')
a('    }')
a('}')

with open(os.path.join(d, "SmartScanViewModel.kt"), "w", encoding="utf-8") as f:
    f.write("\n".join(lines) + "\n")
print("done: SmartScanViewModel.kt")
