import os
path = r"app\src\main\java\com\app\knowledgegraph\ui\practice\PracticeHubScreen.kt"

lines = []
a = lines.append

a('package com.app.knowledgegraph.ui.practice')
a('')
a('import androidx.compose.animation.animateContentSize')
a('import androidx.compose.foundation.background')
a('import androidx.compose.foundation.clickable')
a('import androidx.compose.foundation.horizontalScroll')
a('import androidx.compose.foundation.layout.*')
a('import androidx.compose.foundation.lazy.LazyColumn')
a('import androidx.compose.foundation.lazy.items')
a('import androidx.compose.foundation.rememberScrollState')
a('import androidx.compose.foundation.shape.RoundedCornerShape')
a('import androidx.compose.material.icons.Icons')
a('import androidx.compose.material.icons.filled.*')
a('import androidx.compose.material3.*')
a('import androidx.compose.runtime.*')
a('import androidx.compose.ui.Alignment')
a('import androidx.compose.ui.Modifier')
a('import androidx.compose.ui.draw.clip')
a('import androidx.compose.ui.graphics.Color')
a('import androidx.compose.ui.text.font.FontWeight')
a('import androidx.compose.ui.text.style.TextOverflow')
a('import androidx.compose.ui.unit.dp')
a('import androidx.compose.ui.unit.sp')
a('import com.app.knowledgegraph.AppContainer')
a('import com.app.knowledgegraph.data.db.entity.ImportedQuestion')
a('import com.app.knowledgegraph.data.db.entity.QuestionType')
a('import java.text.SimpleDateFormat')
a('import java.util.Date')
a('import java.util.Locale')
a('')
a('enum class PracticeTab { SETTINGS, QUESTIONS }')
a('')
a('@OptIn(ExperimentalMaterial3Api::class)')
a('@Composable')
a('fun PracticeHubScreen(')
a('    container: AppContainer,')
a('    onNavigateToMethodTraining: () -> Unit,')
a('    onNavigateToScan: () -> Unit,')
a('    onNavigateToQuiz: () -> Unit')
a(') {')
a('    val allQuestions by container.scanRepository.observeAll().collectAsState(initial = emptyList())')
a('    val allSources by container.scanRepository.observeAllSources().collectAsState(initial = emptyList())')
a('    val importedCount by container.scanRepository.observeTotalCount().collectAsState(initial = 0)')
a('')
a('    var selectedTab by remember { mutableStateOf(PracticeTab.SETTINGS) }')
a('')
a('    // Settings state')
a('    var selectedSources by remember { mutableStateOf(setOf<String>()) }')
a('    var selectedTypes by remember { mutableStateOf(setOf<QuestionType>()) }')
a('    var questionCount by remember { mutableIntStateOf(10) }')
a('')
a('    // Question list state')
a('    var searchQuery by remember { mutableStateOf("") }')
a('    var sortByDate by remember { mutableStateOf(true) } // true=newest first')
a('    var filterSource by remember { mutableStateOf<String?>(null) }')
a('')
a('    val filteredQuestions = remember(allQuestions, searchQuery, filterSource, sortByDate) {')
a('        var list = allQuestions')
a('        if (searchQuery.isNotBlank()) {')
a('            list = list.filter { it.stem.contains(searchQuery, ignoreCase = true) || it.answer.contains(searchQuery, ignoreCase = true) }')
a('        }')
a('        if (filterSource != null) {')
a('            list = list.filter { it.source == filterSource }')
a('        }')
a('        if (sortByDate) list.sortedByDescending { it.createdAt } else list.sortedBy { it.createdAt }')
a('    }')
a('')
a('    Box(modifier = Modifier.fillMaxSize()) {')
a('        Column(modifier = Modifier.fillMaxSize().padding(bottom = 56.dp)) {')
a('            TopAppBar(')
a('                title = { Text("Practice") },')
a('                actions = {')
a('                    IconButton(onClick = onNavigateToScan) {')
a('                        Icon(Icons.Default.CameraAlt, "\\u62cd\\u7167\\u5bfc\\u5165")')
a('                    }')
a('                }')
a('            )')
a('')
a('            // Tab Row')
a('            TabRow(')
a('                selectedTabIndex = if (selectedTab == PracticeTab.SETTINGS) 0 else 1,')
a('                modifier = Modifier.padding(horizontal = 16.dp)')
a('            ) {')
a('                Tab(')
a('                    selected = selectedTab == PracticeTab.SETTINGS,')
a('                    onClick = { selectedTab = PracticeTab.SETTINGS },')
a('                    text = { Text("\\u8bad\\u7ec3\\u8bbe\\u7f6e") },')
a('                    icon = { Icon(Icons.Default.Settings, null, modifier = Modifier.size(18.dp)) }')
a('                )')
a('                Tab(')
a('                    selected = selectedTab == PracticeTab.QUESTIONS,')
a('                    onClick = { selectedTab = PracticeTab.QUESTIONS },')
a('                    text = { Text("\\u9898\\u76ee\\u5217\\u8868 ($importedCount)") },')
a('                    icon = { Icon(Icons.Default.List, null, modifier = Modifier.size(18.dp)) }')
a('                )')
a('            }')
a('')
a('            when (selectedTab) {')
a('                PracticeTab.SETTINGS -> SettingsTab(')
a('                    allSources = allSources,')
a('                    selectedSources = selectedSources,')
a('                    onToggleSource = { src ->')
a('                        selectedSources = if (src in selectedSources) selectedSources - src else selectedSources + src')
a('                    },')
a('                    selectedTypes = selectedTypes,')
a('                    onToggleType = { t ->')
a('                        selectedTypes = if (t in selectedTypes) selectedTypes - t else selectedTypes + t')
a('                    },')
a('                    questionCount = questionCount,')
a('                    onCountChange = { questionCount = it },')
a('                    onMethodTraining = onNavigateToMethodTraining')
a('                )')
a('                PracticeTab.QUESTIONS -> QuestionsTab(')
a('                    questions = filteredQuestions,')
a('                    searchQuery = searchQuery,')
a('                    onSearchChange = { searchQuery = it },')
a('                    sortByDate = sortByDate,')
a('                    onToggleSort = { sortByDate = !sortByDate },')
a('                    allSources = allSources,')
a('                    filterSource = filterSource,')
a('                    onFilterSource = { filterSource = if (filterSource == it) null else it }')
a('                )')
a('            }')
a('        }')
a('')
a('        // Bottom start training button - semicircle')
a('        Box(')
a('            modifier = Modifier')
a('                .align(Alignment.BottomCenter)')
a('                .offset(y = (-8).dp),')
a('            contentAlignment = Alignment.Center')
a('        ) {')
a('            Surface(')
a('                onClick = onNavigateToQuiz,')
a('                shape = RoundedCornerShape(topStart = 28.dp, topEnd = 28.dp, bottomStart = 8.dp, bottomEnd = 8.dp),')
a('                color = MaterialTheme.colorScheme.primary,')
a('                shadowElevation = 8.dp,')
a('                modifier = Modifier.size(width = 140.dp, height = 48.dp)')
a('            ) {')
a('                Row(')
a('                    verticalAlignment = Alignment.CenterVertically,')
a('                    horizontalArrangement = Arrangement.Center,')
a('                    modifier = Modifier.fillMaxSize()')
a('                ) {')
a('                    Icon(Icons.Default.PlayArrow, null, tint = MaterialTheme.colorScheme.onPrimary, modifier = Modifier.size(22.dp))')
a('                    Spacer(Modifier.width(4.dp))')
a('                    Text("\\u5f00\\u59cb\\u8bad\\u7ec3", color = MaterialTheme.colorScheme.onPrimary, fontWeight = FontWeight.Bold, fontSize = 15.sp)')
a('                }')
a('            }')
a('        }')
a('    }')
a('}')
a('')
a('@Composable')
a('private fun SettingsTab(')
a('    allSources: List<String>,')
a('    selectedSources: Set<String>,')
a('    onToggleSource: (String) -> Unit,')
a('    selectedTypes: Set<QuestionType>,')
a('    onToggleType: (QuestionType) -> Unit,')
a('    questionCount: Int,')
a('    onCountChange: (Int) -> Unit,')
a('    onMethodTraining: () -> Unit')
a(') {')
a('    LazyColumn(')
a('        modifier = Modifier.fillMaxSize(),')
a('        contentPadding = PaddingValues(16.dp),')
a('        verticalArrangement = Arrangement.spacedBy(16.dp)')
a('    ) {')
a('        // Source filter')
a('        item {')
a('            Text("\\u6765\\u6e90\\u7b5b\\u9009", style = MaterialTheme.typography.titleSmall, fontWeight = FontWeight.Bold)')
a('            Spacer(Modifier.height(8.dp))')
a('            if (allSources.isEmpty()) {')
a('                Text("\\u6682\\u65e0\\u6765\\u6e90\\uff0c\\u8bf7\\u5148\\u5bfc\\u5165\\u9898\\u76ee", style = MaterialTheme.typography.bodyMedium, color = MaterialTheme.colorScheme.onSurfaceVariant)')
a('            } else {')
a('                Row(modifier = Modifier.horizontalScroll(rememberScrollState()), horizontalArrangement = Arrangement.spacedBy(8.dp)) {')
a('                    allSources.forEach { src ->')
a('                        FilterChip(')
a('                            selected = src in selectedSources,')
a('                            onClick = { onToggleSource(src) },')
a('                            label = { Text(src) }')
a('                        )')
a('                    }')
a('                }')
a('            }')
a('        }')
a('')
a('        // Type filter')
a('        item {')
a('            Text("\\u9898\\u578b\\u7b5b\\u9009", style = MaterialTheme.typography.titleSmall, fontWeight = FontWeight.Bold)')
a('            Spacer(Modifier.height(8.dp))')
a('            Row(modifier = Modifier.horizontalScroll(rememberScrollState()), horizontalArrangement = Arrangement.spacedBy(8.dp)) {')
a('                QuestionType.entries.forEach { type ->')
a('                    FilterChip(')
a('                        selected = type in selectedTypes,')
a('                        onClick = { onToggleType(type) },')
a('                        label = { Text(questionTypeLabel(type)) }')
a('                    )')
a('                }')
a('            }')
a('        }')
a('')
a('        // Question count')
a('        item {')
a('            Text("\\u9898\\u76ee\\u6570\\u91cf", style = MaterialTheme.typography.titleSmall, fontWeight = FontWeight.Bold)')
a('            Spacer(Modifier.height(8.dp))')
a('            Row(horizontalArrangement = Arrangement.spacedBy(8.dp)) {')
a('                listOf(5, 10, 20, 50).forEach { count ->')
a('                    FilterChip(')
a('                        selected = questionCount == count,')
a('                        onClick = { onCountChange(count) },')
a('                        label = { Text("$count") }')
a('                    )')
a('                }')
a('            }')
a('        }')
a('')
a('        // Method training entry')
a('        item {')
a('            Spacer(Modifier.height(8.dp))')
a('            Card(modifier = Modifier.fillMaxWidth().clickable { onMethodTraining() }) {')
a('                Row(modifier = Modifier.padding(16.dp), verticalAlignment = Alignment.CenterVertically) {')
a('                    Icon(Icons.Default.FlashOn, null, tint = MaterialTheme.colorScheme.primary, modifier = Modifier.size(32.dp))')
a('                    Spacer(Modifier.width(12.dp))')
a('                    Column(modifier = Modifier.weight(1f)) {')
a('                        Text("\\u9009\\u6cd5\\u8bad\\u7ec3", style = MaterialTheme.typography.titleSmall, fontWeight = FontWeight.Bold)')
a('                        Text("\\u7535\\u8def\\u7406\\u8bba\\u65b9\\u6cd5\\u9009\\u62e9\\u7ec3\\u4e60", style = MaterialTheme.typography.bodySmall, color = MaterialTheme.colorScheme.onSurfaceVariant)')
a('                    }')
a('                    Icon(Icons.Default.ChevronRight, null)')
a('                }')
a('            }')
a('        }')
a('    }')
a('}')
a('')
a('@Composable')
a('private fun QuestionsTab(')
a('    questions: List<ImportedQuestion>,')
a('    searchQuery: String,')
a('    onSearchChange: (String) -> Unit,')
a('    sortByDate: Boolean,')
a('    onToggleSort: () -> Unit,')
a('    allSources: List<String>,')
a('    filterSource: String?,')
a('    onFilterSource: (String) -> Unit')
a(') {')
a('    Column(modifier = Modifier.fillMaxSize()) {')
a('        // Search bar')
a('        OutlinedTextField(')
a('            value = searchQuery,')
a('            onValueChange = onSearchChange,')
a('            modifier = Modifier.fillMaxWidth().padding(horizontal = 16.dp, vertical = 8.dp),')
a('            placeholder = { Text("\\u641c\\u7d22\\u9898\\u76ee...") },')
a('            leadingIcon = { Icon(Icons.Default.Search, null) },')
a('            singleLine = true')
a('        )')
a('')
a('        // Filter row')
a('        Row(')
a('            modifier = Modifier.horizontalScroll(rememberScrollState()).padding(horizontal = 16.dp, vertical = 4.dp),')
a('            horizontalArrangement = Arrangement.spacedBy(8.dp),')
a('            verticalAlignment = Alignment.CenterVertically')
a('        ) {')
a('            // Sort toggle')
a('            FilterChip(')
a('                selected = true,')
a('                onClick = onToggleSort,')
a('                label = { Text(if (sortByDate) "\\u6700\\u65b0\\u4f18\\u5148" else "\\u6700\\u65e9\\u4f18\\u5148") },')
a('                leadingIcon = { Icon(if (sortByDate) Icons.Default.ArrowDownward else Icons.Default.ArrowUpward, null, modifier = Modifier.size(16.dp)) }')
a('            )')
a('            // Source filters')
a('            FilterChip(')
a('                selected = filterSource == null,')
a('                onClick = { onFilterSource("") },')
a('                label = { Text("\\u5168\\u90e8") }')
a('            )')
a('            allSources.forEach { src ->')
a('                FilterChip(')
a('                    selected = filterSource == src,')
a('                    onClick = { onFilterSource(src) },')
a('                    label = { Text(src) }')
a('                )')
a('            }')
a('        }')
a('')
a('        if (questions.isEmpty()) {')
a('            Box(Modifier.fillMaxSize(), contentAlignment = Alignment.Center) {')
a('                Text("\\u6682\\u65e0\\u9898\\u76ee", style = MaterialTheme.typography.bodyLarge, color = MaterialTheme.colorScheme.onSurfaceVariant)')
a('            }')
a('        } else {')
a('            LazyColumn(')
a('                modifier = Modifier.fillMaxSize(),')
a('                contentPadding = PaddingValues(horizontal = 16.dp, vertical = 8.dp),')
a('                verticalArrangement = Arrangement.spacedBy(8.dp)')
a('            ) {')
a('                items(questions, key = { it.id }) { question ->')
a('                    QuestionCard(question)')
a('                }')
a('            }')
a('        }')
a('    }')
a('}')
a('')
a('@Composable')
a('private fun QuestionCard(question: ImportedQuestion) {')
a('    val dateFormat = remember { SimpleDateFormat("MM/dd HH:mm", Locale.getDefault()) }')
a('    Card(modifier = Modifier.fillMaxWidth().animateContentSize()) {')
a('        Column(modifier = Modifier.padding(12.dp)) {')
a('            Row(')
a('                modifier = Modifier.fillMaxWidth(),')
a('                horizontalArrangement = Arrangement.SpaceBetween,')
a('                verticalAlignment = Alignment.CenterVertically')
a('            ) {')
a('                Row(horizontalArrangement = Arrangement.spacedBy(6.dp)) {')
a('                    AssistChip(')
a('                        onClick = {},')
a('                        label = { Text(questionTypeLabel(question.type), style = MaterialTheme.typography.labelSmall) },')
a('                        modifier = Modifier.height(24.dp)')
a('                    )')
a('                    if (question.source.isNotBlank()) {')
a('                        AssistChip(')
a('                            onClick = {},')
a('                            label = { Text(question.source, style = MaterialTheme.typography.labelSmall) },')
a('                            modifier = Modifier.height(24.dp)')
a('                        )')
a('                    }')
a('                }')
a('                Text(dateFormat.format(Date(question.createdAt)), style = MaterialTheme.typography.labelSmall, color = MaterialTheme.colorScheme.onSurfaceVariant)')
a('            }')
a('            Spacer(Modifier.height(6.dp))')
a('            Text(question.stem, style = MaterialTheme.typography.bodyMedium, maxLines = 3, overflow = TextOverflow.Ellipsis)')
a('            if (question.attemptCount > 0) {')
a('                Spacer(Modifier.height(4.dp))')
a('                val rate = if (question.attemptCount > 0) question.correctCount * 100 / question.attemptCount else 0')
a('                Text("\\u7ec3\\u4e60 ${question.attemptCount} \\u6b21 | \\u6b63\\u786e\\u7387 $rate%",')
a('                    style = MaterialTheme.typography.labelSmall,')
a('                    color = if (rate >= 60) MaterialTheme.colorScheme.primary else MaterialTheme.colorScheme.error)')
a('            }')
a('        }')
a('    }')
a('}')
a('')
a('private fun questionTypeLabel(type: QuestionType): String = when (type) {')
a('    QuestionType.SINGLE_CHOICE -> "\\u5355\\u9009"')
a('    QuestionType.MULTI_CHOICE -> "\\u591a\\u9009"')
a('    QuestionType.FILL_BLANK -> "\\u586b\\u7a7a"')
a('    QuestionType.TRUE_FALSE -> "\\u5224\\u65ad"')
a('}')

with open(path, "w", encoding="utf-8") as f:
    f.write("\n".join(lines) + "\n")
print("done: PracticeHubScreen.kt")
